spring: 
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root
