package com.gzz;

import java.text.DecimalFormat;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;

import lombok.extern.slf4j.Slf4j;
@Slf4j
public class Json {
	private static DecimalFormat df = new DecimalFormat("00");
	public static void main(String[] args) {
		int i=1;
		JSONObject json= JSONObject.parseObject(Json.json);
		log.info("json={}",json);
		JSONArray jsonArray = json.getJSONObject("outline").getJSONArray("chapters");
		for (Object object : jsonArray) {
			JSONObject parseObject = JSONObject.parseObject(object.toString());
			String title = parseObject.getString("title");
			JSONArray sections = parseObject.getJSONArray("sections");
			
			for (Object object2 : sections) {
				JSONObject section = JSONObject.parseObject(object2.toString());
				log.info("{}-{}-{}",df.format(i++),title, section.getString("title")) ;
			}
			
		}
	}
	
	private  static String json="{\r\n" + 
			"	\"outline\": {\r\n" + 
			"		\"chapters\": [{\r\n" + 
			"			\"actionType\": 0,\r\n" + 
			"			\"courseId\": 106409,\r\n" + 
			"			\"id\": 8472505,\r\n" + 
			"			\"introduction\": \"\",\r\n" + 
			"			\"isFree\": 0,\r\n" + 
			"			\"learn\": false,\r\n" + 
			"			\"learnPoint\": 0,\r\n" + 
			"			\"lessonLength\": 0,\r\n" + 
			"			\"lessonLengthStr\": \"\",\r\n" + 
			"			\"parentId\": 0,\r\n" + 
			"			\"resources\": [],\r\n" + 
			"			\"sections\": [{\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8579879,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"11:26\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4863849,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 686,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"01-Kubernetes概述\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"01-Kubernetes概述\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8589828,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"10:43\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4776867,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 643,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"02-Kubernetes特性\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"02-Kubernetes特性\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8458845,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"08:16\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4851841,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 496,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"03-Kubernetes架构设计\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"03-Kubernetes架构设计\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8472856,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"07:56\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4778806,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 476,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"04-Kubernetes资源对象pod\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"04-Kubernetes资源对象pod\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8585868,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"14:29\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4776868,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 869,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"05-Kubernetes资源对象汇总\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"05-Kubernetes资源对象汇总\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8575861,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"26:41\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4847835,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1601,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"06-Kubernetes-虚拟机环境设置（一）\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"06-Kubernetes-虚拟机环境设置（一）\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8591880,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"08:03\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4764822,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 483,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"07-Kubernetes-虚拟机环境安装（二）\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"07-Kubernetes-虚拟机环境安装（二）\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8476893,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"29:48\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4770825,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1788,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"08-基于kubeadm部署kubernetes\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"08-基于kubeadm部署kubernetes\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8476894,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"15:34\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4764823,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 934,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"09-基于kubeadm部署kubernetes（node）\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"09-基于kubeadm部署kubernetes（node）\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8466862,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"31:28\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4774814,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1888,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"10-基于kubeadm部署kubernetes\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"10-基于kubeadm部署kubernetes\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8577889,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"33:02\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4762835,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1982,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"11-kubectl命令行工具常用运维命令应用\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"11-kubectl命令行工具常用运维命令应用\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8585869,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"35:15\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4768836,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 2115,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"12-1-通过yaml创建pod对象\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"12-1-通过yaml创建pod对象\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8595866,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"08:25\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4776869,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 505,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"12-2-解决部署pod时image问题\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"12-2-解决部署pod时image问题\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8458846,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"11:10\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4780821,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 670,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"13-pod生命周期与创建过程\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"13-pod生命周期与创建过程\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8470805,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"15:47\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4766828,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 947,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"14-Kubernetes设计理念\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"14-Kubernetes设计理念\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8575862,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"22:39\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4768837,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1359,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"15-Kubernetes核心技术和API对象（官方）\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"15-Kubernetes核心技术和API对象（官方）\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8585870,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"05:51\",\r\n" + 
			"				\"parentId\": 8472505,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4865821,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 351,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"16-Kubernetes-核心组件与通信端口(官方)\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"16-Kubernetes-核心组件与通信端口(官方)\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}],\r\n" + 
			"			\"sellerId\": 2705259897,\r\n" + 
			"			\"status\": 0,\r\n" + 
			"			\"title\": \"Kubernetes入门篇\",\r\n" + 
			"			\"type\": 0\r\n" + 
			"		}, {\r\n" + 
			"			\"actionType\": 0,\r\n" + 
			"			\"courseId\": 106409,\r\n" + 
			"			\"id\": 8573583,\r\n" + 
			"			\"introduction\": \"\",\r\n" + 
			"			\"isFree\": 0,\r\n" + 
			"			\"learn\": false,\r\n" + 
			"			\"learnPoint\": 0,\r\n" + 
			"			\"lessonLength\": 0,\r\n" + 
			"			\"lessonLengthStr\": \"\",\r\n" + 
			"			\"parentId\": 0,\r\n" + 
			"			\"resources\": [],\r\n" + 
			"			\"sections\": [{\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8579880,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"10:05\",\r\n" + 
			"				\"parentId\": 8573583,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4863850,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 605,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"01-k8s核心组件\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"01-k8s核心组件\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8585871,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"17:36\",\r\n" + 
			"				\"parentId\": 8573583,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4762836,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1056,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"02-k8s核心组件-kube-apiserver原理分析\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"02-k8s核心组件-kube-apiserver原理分析\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8573889,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"30:04\",\r\n" + 
			"				\"parentId\": 8573583,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4768838,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1804,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"03-k8s核心组件-kube-scheduler原理分析\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"03-k8s核心组件-kube-scheduler原理分析\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8587853,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"04:46\",\r\n" + 
			"				\"parentId\": 8573583,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4770826,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 286,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"04-k8s核心组件-kube-scheduler(扩展)\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"04-k8s核心组件-kube-scheduler(扩展)\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8464860,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"11:32\",\r\n" + 
			"				\"parentId\": 8573583,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4776870,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 692,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"05-k8s核心组件-ControllerManager原理\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"05-k8s核心组件-ControllerManager原理\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8579881,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"37:06\",\r\n" + 
			"				\"parentId\": 8573583,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4853824,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 2226,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"06-k8s核心组件-Kubelet原理分析\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"06-k8s核心组件-Kubelet原理分析\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8458847,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"37:04\",\r\n" + 
			"				\"parentId\": 8573583,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4849803,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 2224,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"07-k8s核心组件-Kubelet故障排除分析\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"07-k8s核心组件-Kubelet故障排除分析\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}],\r\n" + 
			"			\"sellerId\": 2705259897,\r\n" + 
			"			\"status\": 0,\r\n" + 
			"			\"title\": \"Kubernetes进阶篇\",\r\n" + 
			"			\"type\": 0\r\n" + 
			"		}, {\r\n" + 
			"			\"actionType\": 0,\r\n" + 
			"			\"courseId\": 106409,\r\n" + 
			"			\"id\": 8466512,\r\n" + 
			"			\"introduction\": \"\",\r\n" + 
			"			\"isFree\": 0,\r\n" + 
			"			\"learn\": false,\r\n" + 
			"			\"learnPoint\": 0,\r\n" + 
			"			\"lessonLength\": 0,\r\n" + 
			"			\"lessonLengthStr\": \"\",\r\n" + 
			"			\"parentId\": 0,\r\n" + 
			"			\"resources\": [],\r\n" + 
			"			\"sections\": [{\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8476517,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"05:49\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4768497,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 349,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"00-课程介绍\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"00-课程介绍\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8587524,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"15:27\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4782467,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 927,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"01-Docker简介与工作原理\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"01-Docker简介与工作原理\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8476518,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"16:14\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4764513,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 974,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"02-Docker特性与内部组件\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"02-Docker特性与内部组件\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8579521,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"22:37\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4762476,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1357,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"03-零基础必看此环境搭建教程\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"03-零基础必看此环境搭建教程\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8464537,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"10:31\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4849480,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 631,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"04-Centos7安装Docker\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"04-Centos7安装Docker\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8585533,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"21:19\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4855528,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1279,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"05-Docker基本操作（控制容器）\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"05-Docker基本操作（控制容器）\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8583564,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"12:46\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4770481,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 766,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"06-Docker基本操作（连接容器、删除容器）\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"06-Docker基本操作（连接容器、删除容器）\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8593533,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"29:24\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4774489,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1764,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"07-Docker高级命令\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"07-Docker高级命令\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8591539,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"21:19\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4849481,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1279,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"08-搭建Docker私有仓库\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"08-搭建Docker私有仓库\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8595531,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"27:28\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4762477,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1648,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"09-常用Linuxshell 语法\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"09-常用Linuxshell 语法\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 8468506,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"34:52\",\r\n" + 
			"				\"parentId\": 8466512,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 4762478,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 2092,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"10-创建Docker镜像\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"10-创建Docker镜像\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}],\r\n" + 
			"			\"sellerId\": 2705259897,\r\n" + 
			"			\"status\": 0,\r\n" + 
			"			\"title\": \"docker视频教程\",\r\n" + 
			"			\"type\": 0\r\n" + 
			"		}, {\r\n" + 
			"			\"actionType\": 0,\r\n" + 
			"			\"courseId\": 106409,\r\n" + 
			"			\"id\": 10319111,\r\n" + 
			"			\"introduction\": \"\",\r\n" + 
			"			\"isFree\": 0,\r\n" + 
			"			\"learn\": false,\r\n" + 
			"			\"learnPoint\": 0,\r\n" + 
			"			\"lessonLength\": 0,\r\n" + 
			"			\"lessonLengthStr\": \"\",\r\n" + 
			"			\"parentId\": 0,\r\n" + 
			"			\"resources\": [],\r\n" + 
			"			\"sections\": [{\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 10321131,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"20:03\",\r\n" + 
			"				\"parentId\": 10319111,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5199025,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1203,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"01-Prometheus基本介绍\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"01-Prometheus基本介绍\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 10434050,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"19:25\",\r\n" + 
			"				\"parentId\": 10319111,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5161119,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1165,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"02-prometheus系统环境\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"02-prometheus系统环境\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 10420047,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"16:24\",\r\n" + 
			"				\"parentId\": 10319111,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5187046,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 984,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"03-Prometheus监控指标与部署Exporter\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"03-Prometheus监控指标与部署Exporter\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 10424036,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"13:37\",\r\n" + 
			"				\"parentId\": 10319111,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5199026,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 817,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"04-PrometheusServer和采集监控主机数据\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"04-PrometheusServer和采集监控主机数据\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 10282137,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"10:39\",\r\n" + 
			"				\"parentId\": 10319111,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5132042,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 639,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"05-Prometheus监控数据展示-Grafana配置\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"05-Prometheus监控数据展示-Grafana配置\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 10282138,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"18:58\",\r\n" + 
			"				\"parentId\": 10319111,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5132043,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1138,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"06-AlertManager部署配置邮件告警\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"06-AlertManager部署配置邮件告警\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}],\r\n" + 
			"			\"sellerId\": 2705259897,\r\n" + 
			"			\"status\": 0,\r\n" + 
			"			\"title\": \"prometheus视频教程\",\r\n" + 
			"			\"type\": 0\r\n" + 
			"		}, {\r\n" + 
			"			\"actionType\": 0,\r\n" + 
			"			\"courseId\": 106409,\r\n" + 
			"			\"id\": 11475257,\r\n" + 
			"			\"introduction\": \"\",\r\n" + 
			"			\"isFree\": 0,\r\n" + 
			"			\"learn\": false,\r\n" + 
			"			\"learnPoint\": 0,\r\n" + 
			"			\"lessonLength\": 0,\r\n" + 
			"			\"lessonLengthStr\": \"\",\r\n" + 
			"			\"parentId\": 0,\r\n" + 
			"			\"resources\": [],\r\n" + 
			"			\"sections\": [{\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11477229,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"03:58\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5354243,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 238,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"00-Kubernetes基础部分课程简介\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"00-Kubernetes基础部分课程简介\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11422262,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"15:19\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5340210,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 919,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"01-当今现状应用架构发展\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"01-当今现状应用架构发展\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11471260,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"21:06\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 2\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5437214,\r\n" + 
			"					\"isFree\": 1,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1266,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"02-容器技术的盛行\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"02-容器技术的盛行\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11479236,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"20:41\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5344231,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1241,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"03-1-容器PaaS平台简介\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"03-1-容器PaaS平台简介\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11410236,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"10:42\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5340211,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 642,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"03-2-容器PaaS平台简介\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"03-2-容器PaaS平台简介\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11428251,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"20:32\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5429228,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1232,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"04-1-安装LInux虚拟机环境\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"04-1-安装LInux虚拟机环境\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11422263,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"31:44\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5427207,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1904,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"04-2-安装开发工具和构建工具\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"04-2-安装开发工具和构建工具\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11424254,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"41:28\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5439223,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 2488,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"04-3-容器化springboot应用\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"04-3-容器化springboot应用\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11471261,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"29:15\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5425240,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1755,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"05-1-使用minikube部署k8s集群\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"05-1-使用minikube部署k8s集群\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11479237,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"16:22\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5340212,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 982,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"05-2-使用minikube部署K8S集群\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"05-2-使用minikube部署K8S集群\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11491244,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"26:28\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5439224,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1588,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"05-3-使用脚本自动化部署\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"05-3-使用脚本自动化部署\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11489224,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"18:06\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5435218,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1086,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"06-1-准备基础实验环境\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"06-1-准备基础实验环境\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11410237,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"30:24\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5439225,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1824,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"06-2-安装公共配置部分\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"06-2-安装公共配置部分\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11410238,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"22:28\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5423252,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1348,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"06-3-安装部署K8S集群+控制台\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"06-3-安装部署K8S集群+控制台\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11416232,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"28:53\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5354244,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1733,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"07-1-Kubernetes基本概念\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"07-1-Kubernetes基本概念\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11424255,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"07:24\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5354245,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 444,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"07-2-解决集群node节点not ready问题\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"07-2-解决集群node节点not ready问题\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}, {\r\n" + 
			"				\"actionType\": 0,\r\n" + 
			"				\"courseId\": 106409,\r\n" + 
			"				\"id\": 11475258,\r\n" + 
			"				\"introduction\": \"\",\r\n" + 
			"				\"isFree\": 0,\r\n" + 
			"				\"learn\": false,\r\n" + 
			"				\"learnPoint\": 0,\r\n" + 
			"				\"lessonLength\": 0,\r\n" + 
			"				\"lessonLengthStr\": \"22:58\",\r\n" + 
			"				\"parentId\": 11475257,\r\n" + 
			"				\"resources\": [{\r\n" + 
			"					\"actionType\": 0,\r\n" + 
			"					\"authority\": {\r\n" + 
			"						\"authority\": 1\r\n" + 
			"					},\r\n" + 
			"					\"beginTimeStr1\": \"\",\r\n" + 
			"					\"id\": 5342229,\r\n" + 
			"					\"isFree\": 0,\r\n" + 
			"					\"liveStatus\": 5,\r\n" + 
			"					\"liveToolType\": 0,\r\n" + 
			"					\"playLength\": 1378,\r\n" + 
			"					\"sellerId\": 2705259897,\r\n" + 
			"					\"status\": 0,\r\n" + 
			"					\"title\": \"08-1-通过k8s部署nginxweb应用\",\r\n" + 
			"					\"type\": 1\r\n" + 
			"				}],\r\n" + 
			"				\"sections\": [],\r\n" + 
			"				\"sellerId\": 2705259897,\r\n" + 
			"				\"status\": 0,\r\n" + 
			"				\"title\": \"08-1-通过k8s部署nginxweb应用\",\r\n" + 
			"				\"type\": 0\r\n" + 
			"			}],\r\n" + 
			"			\"sellerId\": 2705259897,\r\n" + 
			"			\"status\": 0,\r\n" + 
			"			\"title\": \"K8s1.15视频教程\",\r\n" + 
			"			\"type\": 0\r\n" + 
			"		}],\r\n" + 
			"		\"courseId\": 106409,\r\n" + 
			"		\"itemId\": 0,\r\n" + 
			"		\"outlineId\": 0,\r\n" + 
			"		\"pcount\": 0\r\n" + 
			"	},\r\n" + 
			"	\"course\": {\r\n" + 
			"		\"courseId\": 106409,\r\n" + 
			"		\"itemId\": 586912529648,\r\n" + 
			"		\"pic\": \"//img.alicdn.com/bao/uploaded/i1/2705259897/O1CN01mFe3dj2MysMO3q8mV_!!2705259897.jpg\",\r\n" + 
			"		\"price\": \"29.90\",\r\n" + 
			"		\"sellerId\": 2705259897,\r\n" + 
			"		\"shopName\": \"宝满服务旗舰店\",\r\n" + 
			"		\"status\": 1,\r\n" + 
			"		\"title\": \"k8s\\\\Kubernetes\\\\docker/prometheus视频教程云计算虚拟化容器集群\",\r\n" + 
			"		\"visible\": true\r\n" + 
			"	},\r\n" + 
			"	\"history\": {\r\n" + 
			"		\"sectionIndex\": 3,\r\n" + 
			"		\"chapterId\": 8472505,\r\n" + 
			"		\"chapterIndex\": 0,\r\n" + 
			"		\"sectionId\": 8472856,\r\n" + 
			"		\"sectionPoint\": 0\r\n" + 
			"	}\r\n" + 
			"}";

}
